---
asn: 61000

transit_vlans:
  - id: "101"
    name: VLAN_101
    vni: 10101
    enabled: true
  - id: "201"
    name: VLAN_201
    vni: 10201
    enabled: true
  - id: "301"
    name: VLAN_301
    vni: 10301
    enabled: true
