---
loopbacks:
  - name: loopback254
    description: "PIM anycast gateway"

loopback_ips:
  - name: loopback254
    ipv4:
      address: 10.10.10.254/32

anycast_rp_peers:
  - 10.10.10.1
  - 10.10.10.2 
  - 10.10.10.3
  - 10.10.10.4 

