---
- name: Configure VLANs on leaf switch ports
  hosts: leafs
  gather_facts: false

  tasks:
    - name: Ensure interfaces are switchports
      cisco.nxos.nxos_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: trunk
      loop: "{{ host_ports }}"

    - name: Configure leaf switch trunk ports
      cisco.nxos.nxos_l2_interfaces:
        config: "{{ host_ports }}"
        state: merged