---
  - name: Create VRFs and apply VNI, route-distinguisher, and route-targets 
    gather_facts: false
    hosts: leafs
    vars:
      l3_vni_l3_vni_vlan_map:
        st1: [101, 201, 301]
        st2: [201, 301, 401]
        st3: [301, 401, 501]
      
    tasks:
      - name: Create VRF, apply VNI and route distinguisher
        cisco.nxos.nxos_vrf_global:
          config:
            vrfs:  |
              {% set site = inventory_hostname.split('-')[1] %}
              {% for l3_vni_vlan in l3_vni_l3_vni_vlan_map[site] %}
              - name: 'vrf_{{ l3_vni_vlan }}'
                description: 'l3_vni_vlan {{ l3_vni_vlan }} | VNI 10{{ l3_vni_vlan }}'
                rd: auto
                vni:
                 layer_3: true
                 vni_number: 10{{ l3_vni_vlan }}
              {% endfor %}
            state: merged
        when: inventory_hostname.split('-')[1] in l3_vni_l3_vni_vlan_map.keys()

      - name: VRF address-family - apply RD and RT
        cisco.nxos.nxos_vrf_af:
          vrf: 'vrf_{{ item }}'
          afi: ipv4
          route_target_both_auto_evpn: true
          state: present
        loop: "{{ l3_vni_l3_vni_vlan_map[inventory_hostname.split('-')[1]] }}"
        when: inventory_hostname.split('-')[1] in l3_vni_l3_vni_vlan_map.keys()
                    
      - name: Verify VRFs
        cisco.nxos.nxos_command:
          commands:
            - show running-config | section ^vrf
        register: print_vrfs

      - name: Show configured VRFs
        debug:
          msg: |
            === {{ inventory_hostname }} ===
            "{{ print_vrfs.stdout[0] }}"
