---
- name: Create VRFVLANs and SVIs
  hosts: leafs
  gather_facts: false

  tasks:
    - name: Create VLANs - ID, name, VNI
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
            mapped_vni: "{{ item.vni }}"
        state: merged
      loop: "{{ vlans }}"

    - name: Create SVIs
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "vlan{{ item.id }}"
            ipv4:
              - address: "{{ item.svi.ip}}"
        state: merged
      loop: "{{ vlans }}"

    - name: Add anycast SVI description
      cisco.nxos.nxos_interfaces: 
        config:
          - name: "vlan{{ item.id }}"
            description: "{{ item.svi.description }}"
            enabled: true
        state: merged
      loop: "{{ vlans }}"

    - name: Show VLANs command
      cisco.nxos.nxos_command:
        commands:
          - "show vlan"
      register: sh_vlans
        
    - name: Show SVIs command
      cisco.nxos.nxos_command:
        commands:
          - "show ip interface brief | i Vlan"
      register: sh_svis

    - name: Show VLANs
      ansible.builtin.debug:
        var: sh_vlans.stdout_lines

    - name: Show SVIs
      ansible.builtin.debug:
        var: sh_svis.stdout_lines
