---
  - name: Create VRFs and apply VNI, route-distinguisher, and route-targets 
    gather_facts: false
    hosts: leafs
    vars:
      vlan_map:
        st1: [100, 200, 300]
        st2: [200, 300, 400]
        st3: [300, 400, 500]
      
    tasks:
      - name: Create VRF, apply VNI and route distinguisher
        cisco.nxos.nxos_vrf_global:
          vrfs: |
            {% set site = inventory_hostname.split('-')[1] %}
            {% for vlan in vlan_map[site] %}
            - name: 'vrf{{ vlan }}'
              description: 'VLAN {{ vlan }} | VNI 10{{ vlan }}'
              rd: auto
              vni:
               layer_3: true
               vni_number: 10{{ vlan }}
            {% endfor %}
          state: merged
        when: inventory_hostname.split('-')[1] in vlan_map.keys()

      - name: VRF address-family - apply RD and RT
        cisco.nxos.nxos_vrf_af:
          vrf: 'vrf{{ item }}'
          afi: ipv4
          route_target_both_auto_evpn: true
          state: present
        loop: "{{ vlan_map[inventory_hostname.split('-')[1]] }}"
        when: inventory_hostname.split('1')[1] in vlan_map.keys()
                    
      - name: Verify VRFs
        cisco.nxos.nxos_command:
          commands:
            - show running-config | section ^vrf
        register: print_vrfs

      - name: Show configured VRFs
        debug:
          msg: |
            === {{ inventory_hostname" }} ===
            "{{ print_vrfs.stdout[0]] }}"
