---
- name: Create VLANs
  hosts: leafs
  gather_facts: false

  tasks:
    - name: Create host VLANs
      cisxo.nxos.nxos_vlans:
        config: "{{ vlans }}"
        state: merged

    - name: Create transit VLANs
      cisxo.nxos.nxos_vlans:
        config: "{{ transit_vlans }}"
        state: merged