---
- name: Verify OSPF neighbors
  hosts: data_switches
  gather_facts: false

  tasks:
    - name: Show OSPF neighbors
      cisco.nxos.nxos_command:
        commands: show ip ospf neighbor
      register: neighbors

    - name: Parse 'show neighbors' output
      ansible.utils.cli_parse:
        text: "{{ neighbors.stdout[0] }}"
        parser:
          name: ansible.netcommon.ntc_templates
          command: show ip ospf neighbor
          os: cisco_nxos
      register: parsed_output
      
    - name: Set parsed neighbors fact
      set_fact:
        parsed_neighbors: "{{ parsed_output.parsed }}"

    - name: Check for incomplete adjacencies
      set_fact:
        incomplete_neighbors: "{{ parsed_neighbors | rejectattr('state', 'search', 'FULL') | list }}"

    - name: All full adjacencies
      debug:
        msg: "++ {{ inventory_hostname }} has all FULL OSPF adjacencies ++"
      when: incomplete_neighbors | length == 0
    
    - name: Display incomplete adjacencies
      debug:
        msg: "{{ inventory_hostname }} has not fully established adjacency with {{ item.neighbor_ipaddr }} on {{ item.interface }} - State: {{ item.state }}"
      loop: "{{ incomplete_neighbors }}"
      when: incomplete_neighbors | length > 0
